### ISSUE TITLE
Crash: There was a severe problem during mod loading that has caused the game to fail

### ISSUE THREAD

**Issue by UndeadZeratul** [UndeadZeratul/TWBB-Tweaks#1]
[![YAMPST - Open source mod pack statistics tracker](http://files.yampst.net/static/banner-small.png)](https://yampst.net/)

Crash report collection powered by [YAMPST](https://yampst.net/).
### Environment data:

| Key | Value |
| --- | --- |
| Mod pack version | 0.4.0 |
| Minecraft version | 1.7.10 |
| Side | Client side |
### Comments by pack administrator:

_No comments._
### Full crash report:

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2/9/16 11:34 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: tconstruct.tools.items.Pattern.getPatternCosts()Ljava/util/Map;
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: tconstruct.tools.items.Pattern.getPatternCosts()Ljava/util/Map;
    at com.undeadzeratul.twbbtweaks.tweaks.TConstructTweaks.getToolPartEntry(TConstructTweaks.java:128)
    at com.undeadzeratul.twbbtweaks.tweaks.TConstructTweaks.buildToolPartEntries(TConstructTweaks.java:115)
    at com.undeadzeratul.twbbtweaks.tweaks.TConstructTweaks.adjustToolPartcosts(TConstructTweaks.java:103)
    at com.undeadzeratul.twbbtweaks.tweaks.TConstructTweaks.init(TConstructTweaks.java:58)
    at com.undeadzeratul.twbbtweaks.TwbbTweaks.initTConstructCompat(TwbbTweaks.java:80)
    at com.undeadzeratul.twbbtweaks.TwbbTweaks.postInit(TwbbTweaks.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    ... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1163987752 bytes (1110 MB) / 2465349632 bytes (2351 MB) up to 3006529536 bytes (2867 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 134 mods loaded, 134 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJ   Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJ   Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJ   CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    UCHIJ   InfiniBows{1.3.0 build 20} [InfiniBows] (minecraft.jar) 
    UCHIJ   itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
    UCHIJ   MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
    UCHIJ   NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJ   OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
    UCHIJ   SomniaCore{1.3.1.55} [SomniaCore] (minecraft.jar) 
    UCHIJ   <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCHIJ   tnt_utilities_core{1.1-beta} [TNTUtils Core] (minecraft.jar) 
    UCHIJ   debug{1.0} [debug] (denseores-1.6.2.jar) 
    UCHIJ   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.2.jar) 
    UCHIJ   nevermine{1.1.1} [Nevermine] (AdventOfAscensionV2.0.jar) 
    UCHIJ   AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft] (AgriCraft-1.7.10-1.4.6-hotfix.jar) 
    UCHIJ   airoverhaul{1.7.10_1.0} [Air Overhaul] (airoverhaul-1.7.10_1.0.jar) 
    UCHIJ   antiqueatlas{1.7.10-4.2.10} [Antique Atlas] (antiqueatlas-1.7.10-4.2.10.jar) 
    UCHIJ   aobdbb{1.0.6} [Another One Bites The Dust: Berry Bushes] (AOBDBB-1.0.6.jar) 
    UCHIJ   AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
    UCHIJ   bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJ   ArmorStatusHUD{1.28} [ArmorStatusHUD] (ArmorStatusHUD-client-1.28.jar) 
    UCHIJ   Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJ   AromaBackup{0.0.0.6} [AromaBackup] (AromaBackup-1.7.10-0.0.0.6.jar) 
    UCHIJ   AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.0.0.6.jar) 
    UCHIJ   CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJ   asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
    UCHIJ   ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
    UCHIJ   excore{1.3.2} [EXCore] (Excore-1.3.2-1.7.10.jar) 
    UCHIJ   avoidexplodingcreepers{2.0} [Avoid Exploding Creepers] (AvoidExplodingCreepers-1.7.10-LATEST.jar) 
    UCHIJ   BetterFoliage{2.0.2} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.2.jar) 
    UCHIJ   Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJ   Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJ   betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
    UCHIJ   BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) 
    UCHIJ   Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
    UCHIJ   Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
    UCHIJ   BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1387-universal.jar) 
    UCHIJ   BlockProperties{0.1.4} [Block Properties] (BlockProperties-1.7.10-0.1.4.jar) 
    UCHIJ   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHIJ   cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
    UCHIJ   cookingbook{1.0.134} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.134.jar) 
    UCHIJ   BuildMod{v1.0} [Build Mod] (coroutil-1.1.2 for MC v1.7.10.jar) 
    UCHIJ   CoroPets{v1.0} [CoroPets] (coroutil-1.1.2 for MC v1.7.10.jar) 
    UCHIJ   CoroAI{v1.0} [CoroAI] (coroutil-1.1.2 for MC v1.7.10.jar) 
    UCHIJ   ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.2 for MC v1.7.10.jar) 
    UCHIJ   ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.2 for MC v1.7.10.jar) 
    UCHIJ   creativecore{1.0} [CreativeCore] (CreativeCore v1.1.2 mc1.7.10.jar) 
    UCHIJ   DamageIndicatorsMod{3.2.3} [Damage Indicators] (DamageIndicatorsMod-3.2.3.jar) 
    UCHIJ   menagerie{1.0} [menagerie] (dark_menagerie-1.7.10-beta-3.1a.jar) 
    UCHIJ   DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) 
    UCHIJ   defaultworldgenerator{0.1-b13} [Default World Generator] (DefaultWorldGenerator-1.7.10-0.1-b13-universal.jar) 
    UCHIJ   dimdoors{2.2.5-test9} [Dimensional Doors] (DimensionalDoors-2.2.5-test9.jar) 
    UCHIJ   DirectionHUD{1.24} [DirectionHUD] (DirectionHUD-client-1.24.jar) 
    UCHIJ   dldungeonsjdg{1.8.5} [Doomlike Dungeons] (DoomlikeDungeons-1.8.5-MC1.7.10.jar) 
    UCHIJ   DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
    UCHIE   Steamcraft{0.28.12} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.12.jar) 
    UCHIJ   hammerz{0.1.7.36} [Hammerz] (Hammerz-1.7.10-0.1.7.36.jar) 
    UCHIJ   HardcoreEnderExpansion{1.8.5} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar) 
    UCHIJ   IguanaTweaks{2B} [Iguana Tweaks] (IguanaTweaks-1.7.10-2B-snapshot-3.jar) 
    UCHIJ   InfernalMobs{1.6.1} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
    UCHIJ   inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
    UCHIJ   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
    UCHIJ   LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
    UCHIJ   lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJ   MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
    UCHIJ   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJ   Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    UCHIJ   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
    UCHIJ   Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
    UCHIJ   meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
    UCHIJ   MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJ   MobProperties{0.4.3} [Mob Properties] (MobProperties-1.7.10-0.4.3.jar) 
    UCHIJ   modpackTweaks{1.2.0} [ModpackTweaks] (ModpackTweaks-MC1.7.10-1.2.0-21.jar) 
    UCHIJ   modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker2-0.9.5.jar) 
    UCHIJ   NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
    UCHIJ   neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
    UCHIJ   NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
    UCHIJ   nincraftlib{1.7.10-0.1.1+24} [Nincraft Lib] (NincraftLib-1.7.10-0.1.1+24.jar) 
    UCHIJ   harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHIJ   temperateplants{1.7.2b} [Pam's Temperate Plants] (Pam's Temperate Plants 1.7.2b.zip) 
    UCHIJ   PneumaticCraft{1.12.4-147} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.4-147-universal.jar) 
    UCHIJ   PoorOres{1.7.10-1.4.8} [PoorOres] (PoorOres-1.7.10-1.4.8.jar) 
    UCHIJ   primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
    UCHIJ   RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
    UCHIJ   RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) 
    UCHIJ   Somnia{-au} [Somnia] (Somnia-1.4.8.55.jar) 
    UCHIJ   soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
    UCHIJ   SpecialAI{1.1.1} [Special AI] (SpecialAI-1.7.10-1.1.1.jar) 
    UCHIJ   SpecialMobs{3.2.1} [Special Mobs] (SpecialMobs-1.7.10-3.2.1.jar) 
    UCHIJ   SpiceOfLife{1.3.0} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.0.jar) 
    UCHIJ   Stackie{1.6.0.36} [Stackie] (Stackie-1.7.10-1.6.0.36-universal.jar) 
    UCHIJ   StatusEffectHUD{1.27} [StatusEffectHUD] (StatusEffectHUD-client-1.27.jar) 
    UCHIJ   thaumcraftneiplugin{1.7.10-1.5} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.5.jar) 
    UCHIJ   tnt_utilities{1.1-beta} [TNTUtils] (tnt_utilities-1.1-beta.jar) 
    UCHIJ   TML{4.0.1} [TooMuchLoot] (TooMuchLoot-1.7.10-4.0.1.B0.jar) 
    UCHIJ   TSteelworks{1.7.10-1.1.1} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.1-17.jar) 
    UCHIE   twbbtweaks{1.7.10-0.0.1+3} [TWBB Tweaks] (TWBBTweaks-1.7.10-0.0.1+3.jar) 
    UCHIJ   TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
    UCHIJ   wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
    UCHIJ   weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) 
    UCHIJ   yampst{1.3.5} [YAMPST] (Yampst-There Will Be Blood-0.4.0.jar) 
    UCHIJ   YeOldeTanks{1.2.0} [Ye Olde Tanks] (YeOldeTanks-1.7.10-1.4.5.jar) 
    UCHIJ   ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) 
    UCHIJ   ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   aobd{2.9.0} [Another One Bites The Dust] (AOBD-2.9.0.jar) 
    UCHIJ   denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
    UCHIJ   HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
    UCHIJ   IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    UCHIJ   ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.1001' Renderer: 'AMD Radeon (TM) R9 390 Series'
    CoFHCore: -[1.7.10]3.0.3-303
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.2.0-102
    TConstruct Environment: Environment healthy.
    NetherOres: -[1.7.10]2.3.0-12
```

**Comment by UndeadZeratul** [comment]
So it looks like this person had TiC 1.8.8 build 988, which they needed build 991.  I can't do anything from here, so I'll close this, but I'll have to look into seeing if I can enforce THAT version of being included.

I don't know how this even happened, both the FTB and Curse launchers should have the right version, and Technic was built manually, so unless I broke something during the pack build process, I don't expect this to be a problem.
